server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
    gateway:
      discovery:
        locator:
          enabled: true
          include-expression: "serviceId.contains('kshop')"