server:
  port: 9002
spring:
  application:
    name: husky-user-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${random.value}
husky:
  swagger:
    enabled: true
    base-package: com.husky.user.spi
    title: 用户服务
    description: 用户服务接口文档
    owner: 卡卡rot~
    email: gexiao_bing@163.com