server:
  port: 9001
spring:
  application:
    name: husky-test-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${random.value}
husky:
  swagger:
    enabled: true
    basePackage: com.husky.test.spi
    title: 测试服务
    description: 测试服务接口文档
    owner: 卡卡rot~
    email: gexiao_bing@163.com